version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      POSTGRES_DB: House-Sharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: razondark
    ports:
      - "5432:5432"
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - default

networks:
  default:
    driver: bridge